---
ID: "18181eba-adb0-4ea0-ac4a-16f33362b823"
Parent: "b900b649-0689-4ee4-972f-85d4797ff8d8"
Template: "4d50cdae-c2d9-4de8-b080-8f992bfb1b55"
Path: /sitecore/content/pentair/pentairpool/Presentation/Headless Variants/Promo CTA/Default
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20260825T211914Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\johannes.zijlstra@sitecore.com
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "dde420ea-c9a6-43a1-afd1-de8416fccea3"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\johannes.zijlstra@sitecore.com
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20260825T211914Z
