---
ID: "3f78155b-8853-402c-bcd0-0887e83e33d9"
Parent: "784cf1e0-5539-44e6-b274-a6a5687ce906"
Template: "784cf1e0-5539-44e6-b274-a6a5687ce906"
Path: /sitecore/templates/Project/Financial/Components/Rendering Parameters/KalTirePromoMosaic/__Standard Values
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20260820T151535Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\johannes.zijlstra@sitecore.com
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\johannes.zijlstra@sitecore.com
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "b09e067f-ab87-4d7b-be69-d9c1b09ac4e2"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\johannes.zijlstra@sitecore.com
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20260820T151535Z
