'use client';
  // This file is auto-generated by the Sitecore Content SDK.
// Below are built-in Content SDK imports neccessary for the import map
import {
  combineImportEntries,
  defaultImportEntries,
  ImportEntry,
} from '@sitecore-content-sdk/nextjs/codegen';
// end of built-in imports

import { jsx, jsxs, Fragment } from 'react/jsx-runtime';
import { useEffect, useState, Suspense, useCallback, useMemo, useRef } from 'react';
import React from 'react';
import { getSiteThemeClass } from 'lib/site-theme';
import { Text, useSitecore, NextImage, Link, RichText, Placeholder, withDatasourceCheck, Image as Image_8a80e63291fea86e0744df19113dc44bec187216, AppPlaceholder, CdpHelper } from '@sitecore-content-sdk/nextjs';
import { useParams, useRouter, useSearchParams, usePathname } from 'next/navigation';
import { useTranslations } from 'next-intl';
import { useSearch } from '@sitecore-content-sdk/nextjs/search';
import { cn } from 'lib/utils';
import { SearchEmptyResults } from 'src/components/search-experience/search-components/SearchEmptyResults';
import { SearchError } from 'src/components/search-experience/search-components/SearchError';
import { SearchItem } from 'src/components/search-experience/search-components/SearchItem/index';
import { SearchSkeletonItem } from 'src/components/search-experience/search-components/SearchSkeletonItem';
import { SearchPagination } from 'src/components/search-experience/search-components/SearchPagination';
import { SearchInput } from 'src/components/search-experience/search-components/SearchInput';
import { useEvent } from 'src/components/search-experience/search-components/useEvent';
import { useSearchField } from 'src/components/search-experience/search-components/useSearchField';
import { useParams as useParams_8e40d23fed0f22fba70acbdfbd79e7011c185841 } from 'src/components/search-experience/search-components/useParams';
import { gridColsClass, DEFAULT_PAGE_SIZE, DEBOUNCE_TIME } from 'src/components/search-experience/search-components/constants';
import { useRouter as useRouter_718da64eaca4c1615fa5f1603d6d6260be2e7c90 } from 'src/components/search-experience/search-components/useRouter';
import { useDebouncedCallback } from 'src/components/search-experience/search-components/useDebounce';
import { event, pageView } from '@sitecore-content-sdk/events';
import { ItemCardFrame, ItemListFrame } from 'src/components/search-experience/search-components/SearchItemCommon';
import Image from 'next/image';
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';
import { faImage } from '@fortawesome/free-solid-svg-icons';
import { cn as cn_f3d36f2085aad61acde9e841f39de9dfc619f8b7 } from 'src/lib/utils';
import { SearchItemTitle } from 'src/components/search-experience/search-components/SearchItem/SearchItemTitle';
import { SearchItemSummary } from 'src/components/search-experience/search-components/SearchItem/SearchItemSummary';
import { SearchItemLink } from 'src/components/search-experience/search-components/SearchItem/SearchItemLink';
import { SearchItemCategory } from 'src/components/search-experience/search-components/SearchItem/SearchItemCategory';
import { SearchItemTags } from 'src/components/search-experience/search-components/SearchItem/SearchItemTags';
import { SearchItemImage } from 'src/components/search-experience/search-components/SearchItem/SearchItemImage';
import { usePreviewSearchActions, useSearchResultsActions, WidgetDataType, usePreviewSearch, widget, useSearchResults, PageController, WidgetsProvider, useQuestions, FilterEqual, useSearchResultsSelectedFilters } from '@sitecore-search/react';
import { PreviewSearch, Pagination, ArticleCard, SortSelect, AccordionFacets, FacetItem, RangeFacet, SearchResultsAccordionFacets, SearchResultsFacetValueRange, Select, CardViewSwitcher as CardViewSwitcher_b6c381477cbf12fc0dc4f9aeb9e8e41e943b6ea7 } from '@sitecore-search/ui';
import { ArrowLeftIcon, ArrowRightIcon, GridIcon, ListBulletIcon, CheckIcon, ChevronDownIcon } from '@radix-ui/react-icons';
import Spinner from 'src/components/search/Spinner';
import SuggestionBlock from 'src/components/search/SuggestionBlock';
import { PREVIEW_WIDGET_ID, HIGHLIGHTED_ARTICLES_RFKID, SEARCH_WIDGET_ID, DEFAULT_IMG_URL, HOMEHIGHLIGHTED_WIDGET_ID } from 'src/_data/customizations';
import { useSearchTracking } from 'src/hooks/useSearchTracking';
import HomeHighlighted from 'src/components/search/HomeHighlighted';
import ArticleItemCard from 'src/components/search/ArticleCard';
import SortOrder from 'src/components/search/SortOrder';
import ArticleHorizontalItemCard from 'src/components/search/ArticleHorizontalCard';
import SearchPagination_de371762291f478adf16c99915fd94e5a978593e from 'src/components/search/StandaloneSearchPagination';
import SearchFacets from 'src/components/search/SearchFacets';
import ResultsPerPage from 'src/components/search/ResultsPerPage';
import QueryResultsSummary from 'src/components/search/QueryResultsSummary';
import CardViewSwitcher from 'src/components/search/CardViewSwitcher';
import SearchResultsWidget from 'src/components/search/SearchResultsComponent';
import QuestionsAnswers from 'src/components/search/QuestionsAnswers';
import { Accordion, Content, Header, Item, Trigger } from '@radix-ui/react-accordion';
import Link_a258c208ba01265ca0aa9c7abae745cc7141aa63 from 'next/link';
import useVisibility from 'src/hooks/useVisibility';
import { Swiper, SwiperSlide } from 'swiper/react';
import { Autoplay, EffectCoverflow, Pagination as Pagination_8dba730cdca19ae0ff3cf106a6e16ccff9e9cae7, Navigation } from 'swiper/modules';
import { CountUp } from 'components/non-sitecore/CountUp';
import { DottedAccent } from 'components/non-sitecore/DottedAccent';
import { FacebookIcon, FacebookShareButton, LinkedinIcon, LinkedinShareButton, TwitterIcon, TwitterShareButton } from 'react-share';
import Head from 'next/head';
import { ParallaxBanner } from 'react-scroll-parallax';
import { ParallaxBackgroundImage } from 'components/non-sitecore/ParallaxBackgroundImage';
import { IconAccent } from 'components/non-sitecore/IconAccent';
import client from 'src/lib/sitecore-client';
import config from 'sitecore.config';

const importMap = [
  {
    module: 'react/jsx-runtime',
    exports: [
      { name: 'jsx', value: jsx },
      { name: 'jsxs', value: jsxs },
      { name: 'Fragment', value: Fragment },
    ]
  },
  {
    module: 'react',
    exports: [
      { name: 'useEffect', value: useEffect },
      { name: 'useState', value: useState },
      { name: 'Suspense', value: Suspense },
      { name: 'useCallback', value: useCallback },
      { name: 'useMemo', value: useMemo },
      { name: 'useRef', value: useRef },
      { name: 'default', value: React },
    ]
  },
  {
    module: 'lib/site-theme',
    exports: [
      { name: 'getSiteThemeClass', value: getSiteThemeClass },
    ]
  },
  {
    module: '@sitecore-content-sdk/nextjs',
    exports: [
      { name: 'Text', value: Text },
      { name: 'useSitecore', value: useSitecore },
      { name: 'NextImage', value: NextImage },
      { name: 'Link', value: Link },
      { name: 'RichText', value: RichText },
      { name: 'Placeholder', value: Placeholder },
      { name: 'withDatasourceCheck', value: withDatasourceCheck },
      { name: 'Image', value: Image_8a80e63291fea86e0744df19113dc44bec187216 },
      { name: 'AppPlaceholder', value: AppPlaceholder },
      { name: 'CdpHelper', value: CdpHelper },
    ]
  },
  {
    module: 'next/navigation',
    exports: [
      { name: 'useParams', value: useParams },
      { name: 'useRouter', value: useRouter },
      { name: 'useSearchParams', value: useSearchParams },
      { name: 'usePathname', value: usePathname },
    ]
  },
  {
    module: 'next-intl',
    exports: [
      { name: 'useTranslations', value: useTranslations },
    ]
  },
  {
    module: '@sitecore-content-sdk/nextjs/search',
    exports: [
      { name: 'useSearch', value: useSearch },
    ]
  },
  {
    module: 'lib/utils',
    exports: [
      { name: 'cn', value: cn },
    ]
  },
  {
    module: 'src/components/search-experience/search-components/SearchEmptyResults',
    exports: [
      { name: 'SearchEmptyResults', value: SearchEmptyResults },
    ]
  },
  {
    module: 'src/components/search-experience/search-components/SearchError',
    exports: [
      { name: 'SearchError', value: SearchError },
    ]
  },
  {
    module: 'src/components/search-experience/search-components/SearchItem/index',
    exports: [
      { name: 'SearchItem', value: SearchItem },
    ]
  },
  {
    module: 'src/components/search-experience/search-components/SearchSkeletonItem',
    exports: [
      { name: 'SearchSkeletonItem', value: SearchSkeletonItem },
    ]
  },
  {
    module: 'src/components/search-experience/search-components/SearchPagination',
    exports: [
      { name: 'SearchPagination', value: SearchPagination },
    ]
  },
  {
    module: 'src/components/search-experience/search-components/SearchInput',
    exports: [
      { name: 'SearchInput', value: SearchInput },
    ]
  },
  {
    module: 'src/components/search-experience/search-components/useEvent',
    exports: [
      { name: 'useEvent', value: useEvent },
    ]
  },
  {
    module: 'src/components/search-experience/search-components/useSearchField',
    exports: [
      { name: 'useSearchField', value: useSearchField },
    ]
  },
  {
    module: 'src/components/search-experience/search-components/useParams',
    exports: [
      { name: 'useParams', value: useParams_8e40d23fed0f22fba70acbdfbd79e7011c185841 },
    ]
  },
  {
    module: 'src/components/search-experience/search-components/constants',
    exports: [
      { name: 'gridColsClass', value: gridColsClass },
      { name: 'DEFAULT_PAGE_SIZE', value: DEFAULT_PAGE_SIZE },
      { name: 'DEBOUNCE_TIME', value: DEBOUNCE_TIME },
    ]
  },
  {
    module: 'src/components/search-experience/search-components/useRouter',
    exports: [
      { name: 'useRouter', value: useRouter_718da64eaca4c1615fa5f1603d6d6260be2e7c90 },
    ]
  },
  {
    module: 'src/components/search-experience/search-components/useDebounce',
    exports: [
      { name: 'useDebouncedCallback', value: useDebouncedCallback },
    ]
  },
  {
    module: '@sitecore-content-sdk/events',
    exports: [
      { name: 'event', value: event },
      { name: 'pageView', value: pageView },
    ]
  },
  {
    module: 'src/components/search-experience/search-components/SearchItemCommon',
    exports: [
      { name: 'ItemCardFrame', value: ItemCardFrame },
      { name: 'ItemListFrame', value: ItemListFrame },
    ]
  },
  {
    module: 'next/image',
    exports: [
      { name: 'default', value: Image },
    ]
  },
  {
    module: '@fortawesome/react-fontawesome',
    exports: [
      { name: 'FontAwesomeIcon', value: FontAwesomeIcon },
    ]
  },
  {
    module: '@fortawesome/free-solid-svg-icons',
    exports: [
      { name: 'faImage', value: faImage },
    ]
  },
  {
    module: 'src/lib/utils',
    exports: [
      { name: 'cn', value: cn_f3d36f2085aad61acde9e841f39de9dfc619f8b7 },
    ]
  },
  {
    module: 'src/components/search-experience/search-components/SearchItem/SearchItemTitle',
    exports: [
      { name: 'SearchItemTitle', value: SearchItemTitle },
    ]
  },
  {
    module: 'src/components/search-experience/search-components/SearchItem/SearchItemSummary',
    exports: [
      { name: 'SearchItemSummary', value: SearchItemSummary },
    ]
  },
  {
    module: 'src/components/search-experience/search-components/SearchItem/SearchItemLink',
    exports: [
      { name: 'SearchItemLink', value: SearchItemLink },
    ]
  },
  {
    module: 'src/components/search-experience/search-components/SearchItem/SearchItemCategory',
    exports: [
      { name: 'SearchItemCategory', value: SearchItemCategory },
    ]
  },
  {
    module: 'src/components/search-experience/search-components/SearchItem/SearchItemTags',
    exports: [
      { name: 'SearchItemTags', value: SearchItemTags },
    ]
  },
  {
    module: 'src/components/search-experience/search-components/SearchItem/SearchItemImage',
    exports: [
      { name: 'SearchItemImage', value: SearchItemImage },
    ]
  },
  {
    module: '@sitecore-search/react',
    exports: [
      { name: 'usePreviewSearchActions', value: usePreviewSearchActions },
      { name: 'useSearchResultsActions', value: useSearchResultsActions },
      { name: 'WidgetDataType', value: WidgetDataType },
      { name: 'usePreviewSearch', value: usePreviewSearch },
      { name: 'widget', value: widget },
      { name: 'useSearchResults', value: useSearchResults },
      { name: 'PageController', value: PageController },
      { name: 'WidgetsProvider', value: WidgetsProvider },
      { name: 'useQuestions', value: useQuestions },
      { name: 'FilterEqual', value: FilterEqual },
      { name: 'useSearchResultsSelectedFilters', value: useSearchResultsSelectedFilters },
    ]
  },
  {
    module: '@sitecore-search/ui',
    exports: [
      { name: 'PreviewSearch', value: PreviewSearch },
      { name: 'Pagination', value: Pagination },
      { name: 'ArticleCard', value: ArticleCard },
      { name: 'SortSelect', value: SortSelect },
      { name: 'AccordionFacets', value: AccordionFacets },
      { name: 'FacetItem', value: FacetItem },
      { name: 'RangeFacet', value: RangeFacet },
      { name: 'SearchResultsAccordionFacets', value: SearchResultsAccordionFacets },
      { name: 'SearchResultsFacetValueRange', value: SearchResultsFacetValueRange },
      { name: 'Select', value: Select },
      { name: 'CardViewSwitcher', value: CardViewSwitcher_b6c381477cbf12fc0dc4f9aeb9e8e41e943b6ea7 },
    ]
  },
  {
    module: '@radix-ui/react-icons',
    exports: [
      { name: 'ArrowLeftIcon', value: ArrowLeftIcon },
      { name: 'ArrowRightIcon', value: ArrowRightIcon },
      { name: 'GridIcon', value: GridIcon },
      { name: 'ListBulletIcon', value: ListBulletIcon },
      { name: 'CheckIcon', value: CheckIcon },
      { name: 'ChevronDownIcon', value: ChevronDownIcon },
    ]
  },
  {
    module: 'src/components/search/Spinner',
    exports: [
      { name: 'default', value: Spinner },
    ]
  },
  {
    module: 'src/components/search/SuggestionBlock',
    exports: [
      { name: 'default', value: SuggestionBlock },
    ]
  },
  {
    module: 'src/_data/customizations',
    exports: [
      { name: 'PREVIEW_WIDGET_ID', value: PREVIEW_WIDGET_ID },
      { name: 'HIGHLIGHTED_ARTICLES_RFKID', value: HIGHLIGHTED_ARTICLES_RFKID },
      { name: 'SEARCH_WIDGET_ID', value: SEARCH_WIDGET_ID },
      { name: 'DEFAULT_IMG_URL', value: DEFAULT_IMG_URL },
      { name: 'HOMEHIGHLIGHTED_WIDGET_ID', value: HOMEHIGHLIGHTED_WIDGET_ID },
    ]
  },
  {
    module: 'src/hooks/useSearchTracking',
    exports: [
      { name: 'useSearchTracking', value: useSearchTracking },
    ]
  },
  {
    module: 'src/components/search/HomeHighlighted',
    exports: [
      { name: 'default', value: HomeHighlighted },
    ]
  },
  {
    module: 'src/components/search/ArticleCard',
    exports: [
      { name: 'default', value: ArticleItemCard },
    ]
  },
  {
    module: 'src/components/search/SortOrder',
    exports: [
      { name: 'default', value: SortOrder },
    ]
  },
  {
    module: 'src/components/search/ArticleHorizontalCard',
    exports: [
      { name: 'default', value: ArticleHorizontalItemCard },
    ]
  },
  {
    module: 'src/components/search/StandaloneSearchPagination',
    exports: [
      { name: 'default', value: SearchPagination_de371762291f478adf16c99915fd94e5a978593e },
    ]
  },
  {
    module: 'src/components/search/SearchFacets',
    exports: [
      { name: 'default', value: SearchFacets },
    ]
  },
  {
    module: 'src/components/search/ResultsPerPage',
    exports: [
      { name: 'default', value: ResultsPerPage },
    ]
  },
  {
    module: 'src/components/search/QueryResultsSummary',
    exports: [
      { name: 'default', value: QueryResultsSummary },
    ]
  },
  {
    module: 'src/components/search/CardViewSwitcher',
    exports: [
      { name: 'default', value: CardViewSwitcher },
    ]
  },
  {
    module: 'src/components/search/SearchResultsComponent',
    exports: [
      { name: 'default', value: SearchResultsWidget },
    ]
  },
  {
    module: 'src/components/search/QuestionsAnswers',
    exports: [
      { name: 'default', value: QuestionsAnswers },
    ]
  },
  {
    module: '@radix-ui/react-accordion',
    exports: [
      { name: 'Accordion', value: Accordion },
      { name: 'Content', value: Content },
      { name: 'Header', value: Header },
      { name: 'Item', value: Item },
      { name: 'Trigger', value: Trigger },
    ]
  },
  {
    module: 'next/link',
    exports: [
      { name: 'default', value: Link_a258c208ba01265ca0aa9c7abae745cc7141aa63 },
    ]
  },
  {
    module: 'src/hooks/useVisibility',
    exports: [
      { name: 'default', value: useVisibility },
    ]
  },
  {
    module: 'swiper/react',
    exports: [
      { name: 'Swiper', value: Swiper },
      { name: 'SwiperSlide', value: SwiperSlide },
    ]
  },
  {
    module: 'swiper/modules',
    exports: [
      { name: 'Autoplay', value: Autoplay },
      { name: 'EffectCoverflow', value: EffectCoverflow },
      { name: 'Pagination', value: Pagination_8dba730cdca19ae0ff3cf106a6e16ccff9e9cae7 },
      { name: 'Navigation', value: Navigation },
    ]
  },
  {
    module: 'components/non-sitecore/CountUp',
    exports: [
      { name: 'CountUp', value: CountUp },
    ]
  },
  {
    module: 'components/non-sitecore/DottedAccent',
    exports: [
      { name: 'DottedAccent', value: DottedAccent },
    ]
  },
  {
    module: 'react-share',
    exports: [
      { name: 'FacebookIcon', value: FacebookIcon },
      { name: 'FacebookShareButton', value: FacebookShareButton },
      { name: 'LinkedinIcon', value: LinkedinIcon },
      { name: 'LinkedinShareButton', value: LinkedinShareButton },
      { name: 'TwitterIcon', value: TwitterIcon },
      { name: 'TwitterShareButton', value: TwitterShareButton },
    ]
  },
  {
    module: 'next/head',
    exports: [
      { name: 'default', value: Head },
    ]
  },
  {
    module: 'react-scroll-parallax',
    exports: [
      { name: 'ParallaxBanner', value: ParallaxBanner },
    ]
  },
  {
    module: 'components/non-sitecore/ParallaxBackgroundImage',
    exports: [
      { name: 'ParallaxBackgroundImage', value: ParallaxBackgroundImage },
    ]
  },
  {
    module: 'components/non-sitecore/IconAccent',
    exports: [
      { name: 'IconAccent', value: IconAccent },
    ]
  },
  {
    module: 'src/lib/sitecore-client',
    exports: [
      { name: 'default', value: client },
    ]
  },
  {
    module: 'sitecore.config',
    exports: [
      { name: 'default', value: config },
    ]
  }
] as ImportEntry[];

export default combineImportEntries(defaultImportEntries, importMap);
