---
ID: "bc78abf6-62d1-4ab6-a5af-4d63fd022215"
Parent: "812e0d16-08a1-4c5b-8926-9f86c6ce5db6"
Template: "4d50cdae-c2d9-4de8-b080-8f992bfb1b55"
Path: "/sitecore/content/public-sector/mns/Presentation/Headless Variants/Article List/Default"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20260831T193750Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\johannes.zijlstra@sitecore.com
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "104f4647-7883-448b-b13b-f9efd3a8805a"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\johannes.zijlstra@sitecore.com
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20260831T193750Z
