// This file is auto-generated by the Sitecore Content SDK.
// Below are built-in Content SDK imports neccessary for the import map
import {
  combineImportEntries,
  defaultServerImportEntries,
  ImportEntry,
} from '@sitecore-content-sdk/nextjs/codegen';
// end of built-in imports

import { jsxs, jsx } from 'react/jsx-runtime';
import componentMap from '.sitecore/component-map';
import { AppPlaceholder } from '@sitecore-content-sdk/nextjs';
import { clsx } from 'clsx';
import { twMerge } from 'tailwind-merge';

const importMap = [
  {
    module: 'react/jsx-runtime',
    exports: [
      { name: 'jsxs', value: jsxs },
      { name: 'jsx', value: jsx },
    ]
  },
  {
    module: '.sitecore/component-map',
    exports: [
      { name: 'default', value: componentMap },
    ]
  },
  {
    module: '@sitecore-content-sdk/nextjs',
    exports: [
      { name: 'AppPlaceholder', value: AppPlaceholder },
    ]
  },
  {
    module: 'clsx',
    exports: [
      { name: 'clsx', value: clsx },
    ]
  },
  {
    module: 'tailwind-merge',
    exports: [
      { name: 'twMerge', value: twMerge },
    ]
  }
] as ImportEntry[];

export default combineImportEntries(defaultServerImportEntries, importMap);
