---
ID: "dfc563e8-8301-48bc-bc8d-ba2af4bf7012"
Parent: "01d9cc90-2228-4c7d-9d89-c5637ccc8395"
Template: "fe5dd826-48c6-436d-b87a-7c4210c7413b"
Path: /sitecore/media library/Project/Financial/hhc/Home page/Carousels/Default
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20251028T215331Z
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "de9d166b-c27d-4b49-b363-8c6f63ad08bf"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\johannes.zijlstra@sitecore.com
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20260623T190256Z
