---
ID: "43181513-88c4-431d-bf89-72dbbb3d32d4"
Parent: "6f57abbb-55ef-408a-954a-d6e48d442279"
Template: "fe5dd826-48c6-436d-b87a-7c4210c7413b"
Path: "/sitecore/media library/Project/Financial/suffolk-county/Home page/Carousels/Default"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20251028T215331Z
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "c61d3d6e-eb25-4d19-9bcf-da8aa22ef3cd"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\johannes.zijlstra@sitecore.com
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20260818T140148Z
