---
ID: "c905384c-aeb5-4151-a210-e877029865f7"
Parent: "fdd12c2d-25b8-4770-a083-eee1f3b0e3cf"
Template: "4d50cdae-c2d9-4de8-b080-8f992bfb1b55"
Path: /sitecore/content/pentair/pentairpool/Presentation/Headless Variants/Article List/Default
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20260825T211913Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\johannes.zijlstra@sitecore.com
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "e4865d9e-6057-46a7-aac5-f545dbd1e5e8"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\johannes.zijlstra@sitecore.com
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20260825T211913Z
