---
ID: "54e3cdd5-8f76-4b2a-ad46-7df1be729ae2"
Parent: "0811f9c5-ab4b-4b5e-a412-bb2c33aa8d73"
Template: "0811f9c5-ab4b-4b5e-a412-bb2c33aa8d73"
Path: /sitecore/templates/Project/pentair/Page Design Folder/__Standard Values
SharedFields:
- ID: "1172f251-dad4-4efb-a329-0c63500e4f1e"
  Hint: __Masters
  Value: |
    {0811F9C5-AB4B-4B5E-A412-BB2C33AA8D73}
    {1105B8F8-1E00-426B-BF1F-C840742D827B}
- ID: "dbbbeca1-21c7-4906-9dd2-493c1efa59a2"
  Hint: __Shared revision
  Value: "72b6e6d2-8273-4580-9a1f-40e8ad66549e"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20260825T202159Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\johannes.zijlstra@sitecore.com
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\johannes.zijlstra@sitecore.com
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "498ceb14-70dc-40a6-bda4-ddc3ff1f7024"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\johannes.zijlstra@sitecore.com
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20260825T202203Z
