'use client';
  // This file is auto-generated by the Sitecore Content SDK.
// Below are built-in Content SDK imports neccessary for the import map
import {
  combineImportEntries,
  defaultImportEntries,
  ImportEntry,
} from '@sitecore-content-sdk/nextjs/codegen';
// end of built-in imports

import { jsx, jsxs, Fragment } from 'react/jsx-runtime';
import { useEffect, useState, Suspense, useCallback, useMemo, useRef } from 'react';
import React from 'react';
import { getSiteThemeClass } from 'lib/site-theme';
import { Text, useSitecore, NextImage, Link, RichText, Placeholder, withDatasourceCheck, Image as Image_8a80e63291fea86e0744df19113dc44bec187216, AppPlaceholder, CdpHelper } from '@sitecore-content-sdk/nextjs';
import { useParams, useRouter, useSearchParams } from 'next/navigation';
import { usePreviewSearchActions, useSearchResultsActions, WidgetDataType, useSearchResults, widget, PageController, WidgetsProvider, useQuestions, usePreviewSearch, FilterEqual, useSearchResultsSelectedFilters } from '@sitecore-search/react';
import { PreviewSearch, SortSelect, Pagination, AccordionFacets, FacetItem, RangeFacet, SearchResultsAccordionFacets, SearchResultsFacetValueRange, Select, ArticleCard, CardViewSwitcher as CardViewSwitcher_b6c381477cbf12fc0dc4f9aeb9e8e41e943b6ea7 } from '@sitecore-search/ui';
import { GridIcon, ListBulletIcon, ArrowLeftIcon, ArrowRightIcon, CheckIcon, ChevronDownIcon } from '@radix-ui/react-icons';
import { HIGHLIGHTED_ARTICLES_RFKID, SEARCH_WIDGET_ID, PREVIEW_WIDGET_ID, DEFAULT_IMG_URL, HOMEHIGHLIGHTED_WIDGET_ID } from 'src/_data/customizations';
import HomeHighlighted from 'src/components/search/HomeHighlighted';
import Spinner from 'src/components/search/Spinner';
import ArticleItemCard from 'src/components/search/ArticleCard';
import SortOrder from 'src/components/search/SortOrder';
import ArticleHorizontalItemCard from 'src/components/search/ArticleHorizontalCard';
import SearchPagination from 'src/components/search/SearchPagination';
import SearchFacets from 'src/components/search/SearchFacets';
import ResultsPerPage from 'src/components/search/ResultsPerPage';
import QueryResultsSummary from 'src/components/search/QueryResultsSummary';
import CardViewSwitcher from 'src/components/search/CardViewSwitcher';
import { useSearchTracking } from 'src/hooks/useSearchTracking';
import SearchResultsWidget from 'src/components/search/SearchResultsComponent';
import QuestionsAnswers from 'src/components/search/QuestionsAnswers';
import { Accordion, Content, Header, Item, Trigger } from '@radix-ui/react-accordion';
import Image from 'next/image';
import SuggestionBlock from 'src/components/search/SuggestionBlock';
import Link_a258c208ba01265ca0aa9c7abae745cc7141aa63 from 'next/link';
import useVisibility from 'src/hooks/useVisibility';
import { Swiper, SwiperSlide } from 'swiper/react';
import { Autoplay, EffectCoverflow, Pagination as Pagination_8dba730cdca19ae0ff3cf106a6e16ccff9e9cae7, Navigation } from 'swiper/modules';
import { CountUp } from 'components/non-sitecore/CountUp';
import { DottedAccent } from 'components/non-sitecore/DottedAccent';
import { FacebookIcon, FacebookShareButton, LinkedinIcon, LinkedinShareButton, TwitterIcon, TwitterShareButton } from 'react-share';
import Head from 'next/head';
import { ParallaxBanner } from 'react-scroll-parallax';
import { ParallaxBackgroundImage } from 'components/non-sitecore/ParallaxBackgroundImage';
import { IconAccent } from 'components/non-sitecore/IconAccent';
import PreviewSearch_4de1a796917131c02c1d8f23d3df1bc9d5bbcf97 from 'src/components/search/PreviewSearch';
import { Default } from 'components/utilities/LanguageSwitcher';
import { Default as Default_82849cdc64a1386caf2bc2113719a7485562c8a0 } from 'components/utilities/ThemeSwitcher';
import client from 'src/lib/sitecore-client';
import { pageView } from '@sitecore-content-sdk/events';
import config from 'sitecore.config';

const importMap = [
  {
    module: 'react/jsx-runtime',
    exports: [
      { name: 'jsx', value: jsx },
      { name: 'jsxs', value: jsxs },
      { name: 'Fragment', value: Fragment },
    ]
  },
  {
    module: 'react',
    exports: [
      { name: 'useEffect', value: useEffect },
      { name: 'useState', value: useState },
      { name: 'Suspense', value: Suspense },
      { name: 'useCallback', value: useCallback },
      { name: 'useMemo', value: useMemo },
      { name: 'useRef', value: useRef },
      { name: 'default', value: React },
    ]
  },
  {
    module: 'lib/site-theme',
    exports: [
      { name: 'getSiteThemeClass', value: getSiteThemeClass },
    ]
  },
  {
    module: '@sitecore-content-sdk/nextjs',
    exports: [
      { name: 'Text', value: Text },
      { name: 'useSitecore', value: useSitecore },
      { name: 'NextImage', value: NextImage },
      { name: 'Link', value: Link },
      { name: 'RichText', value: RichText },
      { name: 'Placeholder', value: Placeholder },
      { name: 'withDatasourceCheck', value: withDatasourceCheck },
      { name: 'Image', value: Image_8a80e63291fea86e0744df19113dc44bec187216 },
      { name: 'AppPlaceholder', value: AppPlaceholder },
      { name: 'CdpHelper', value: CdpHelper },
    ]
  },
  {
    module: 'next/navigation',
    exports: [
      { name: 'useParams', value: useParams },
      { name: 'useRouter', value: useRouter },
      { name: 'useSearchParams', value: useSearchParams },
    ]
  },
  {
    module: '@sitecore-search/react',
    exports: [
      { name: 'usePreviewSearchActions', value: usePreviewSearchActions },
      { name: 'useSearchResultsActions', value: useSearchResultsActions },
      { name: 'WidgetDataType', value: WidgetDataType },
      { name: 'useSearchResults', value: useSearchResults },
      { name: 'widget', value: widget },
      { name: 'PageController', value: PageController },
      { name: 'WidgetsProvider', value: WidgetsProvider },
      { name: 'useQuestions', value: useQuestions },
      { name: 'usePreviewSearch', value: usePreviewSearch },
      { name: 'FilterEqual', value: FilterEqual },
      { name: 'useSearchResultsSelectedFilters', value: useSearchResultsSelectedFilters },
    ]
  },
  {
    module: '@sitecore-search/ui',
    exports: [
      { name: 'PreviewSearch', value: PreviewSearch },
      { name: 'SortSelect', value: SortSelect },
      { name: 'Pagination', value: Pagination },
      { name: 'AccordionFacets', value: AccordionFacets },
      { name: 'FacetItem', value: FacetItem },
      { name: 'RangeFacet', value: RangeFacet },
      { name: 'SearchResultsAccordionFacets', value: SearchResultsAccordionFacets },
      { name: 'SearchResultsFacetValueRange', value: SearchResultsFacetValueRange },
      { name: 'Select', value: Select },
      { name: 'ArticleCard', value: ArticleCard },
      { name: 'CardViewSwitcher', value: CardViewSwitcher_b6c381477cbf12fc0dc4f9aeb9e8e41e943b6ea7 },
    ]
  },
  {
    module: '@radix-ui/react-icons',
    exports: [
      { name: 'GridIcon', value: GridIcon },
      { name: 'ListBulletIcon', value: ListBulletIcon },
      { name: 'ArrowLeftIcon', value: ArrowLeftIcon },
      { name: 'ArrowRightIcon', value: ArrowRightIcon },
      { name: 'CheckIcon', value: CheckIcon },
      { name: 'ChevronDownIcon', value: ChevronDownIcon },
    ]
  },
  {
    module: 'src/_data/customizations',
    exports: [
      { name: 'HIGHLIGHTED_ARTICLES_RFKID', value: HIGHLIGHTED_ARTICLES_RFKID },
      { name: 'SEARCH_WIDGET_ID', value: SEARCH_WIDGET_ID },
      { name: 'PREVIEW_WIDGET_ID', value: PREVIEW_WIDGET_ID },
      { name: 'DEFAULT_IMG_URL', value: DEFAULT_IMG_URL },
      { name: 'HOMEHIGHLIGHTED_WIDGET_ID', value: HOMEHIGHLIGHTED_WIDGET_ID },
    ]
  },
  {
    module: 'src/components/search/HomeHighlighted',
    exports: [
      { name: 'default', value: HomeHighlighted },
    ]
  },
  {
    module: 'src/components/search/Spinner',
    exports: [
      { name: 'default', value: Spinner },
    ]
  },
  {
    module: 'src/components/search/ArticleCard',
    exports: [
      { name: 'default', value: ArticleItemCard },
    ]
  },
  {
    module: 'src/components/search/SortOrder',
    exports: [
      { name: 'default', value: SortOrder },
    ]
  },
  {
    module: 'src/components/search/ArticleHorizontalCard',
    exports: [
      { name: 'default', value: ArticleHorizontalItemCard },
    ]
  },
  {
    module: 'src/components/search/SearchPagination',
    exports: [
      { name: 'default', value: SearchPagination },
    ]
  },
  {
    module: 'src/components/search/SearchFacets',
    exports: [
      { name: 'default', value: SearchFacets },
    ]
  },
  {
    module: 'src/components/search/ResultsPerPage',
    exports: [
      { name: 'default', value: ResultsPerPage },
    ]
  },
  {
    module: 'src/components/search/QueryResultsSummary',
    exports: [
      { name: 'default', value: QueryResultsSummary },
    ]
  },
  {
    module: 'src/components/search/CardViewSwitcher',
    exports: [
      { name: 'default', value: CardViewSwitcher },
    ]
  },
  {
    module: 'src/hooks/useSearchTracking',
    exports: [
      { name: 'useSearchTracking', value: useSearchTracking },
    ]
  },
  {
    module: 'src/components/search/SearchResultsComponent',
    exports: [
      { name: 'default', value: SearchResultsWidget },
    ]
  },
  {
    module: 'src/components/search/QuestionsAnswers',
    exports: [
      { name: 'default', value: QuestionsAnswers },
    ]
  },
  {
    module: '@radix-ui/react-accordion',
    exports: [
      { name: 'Accordion', value: Accordion },
      { name: 'Content', value: Content },
      { name: 'Header', value: Header },
      { name: 'Item', value: Item },
      { name: 'Trigger', value: Trigger },
    ]
  },
  {
    module: 'next/image',
    exports: [
      { name: 'default', value: Image },
    ]
  },
  {
    module: 'src/components/search/SuggestionBlock',
    exports: [
      { name: 'default', value: SuggestionBlock },
    ]
  },
  {
    module: 'next/link',
    exports: [
      { name: 'default', value: Link_a258c208ba01265ca0aa9c7abae745cc7141aa63 },
    ]
  },
  {
    module: 'src/hooks/useVisibility',
    exports: [
      { name: 'default', value: useVisibility },
    ]
  },
  {
    module: 'swiper/react',
    exports: [
      { name: 'Swiper', value: Swiper },
      { name: 'SwiperSlide', value: SwiperSlide },
    ]
  },
  {
    module: 'swiper/modules',
    exports: [
      { name: 'Autoplay', value: Autoplay },
      { name: 'EffectCoverflow', value: EffectCoverflow },
      { name: 'Pagination', value: Pagination_8dba730cdca19ae0ff3cf106a6e16ccff9e9cae7 },
      { name: 'Navigation', value: Navigation },
    ]
  },
  {
    module: 'components/non-sitecore/CountUp',
    exports: [
      { name: 'CountUp', value: CountUp },
    ]
  },
  {
    module: 'components/non-sitecore/DottedAccent',
    exports: [
      { name: 'DottedAccent', value: DottedAccent },
    ]
  },
  {
    module: 'react-share',
    exports: [
      { name: 'FacebookIcon', value: FacebookIcon },
      { name: 'FacebookShareButton', value: FacebookShareButton },
      { name: 'LinkedinIcon', value: LinkedinIcon },
      { name: 'LinkedinShareButton', value: LinkedinShareButton },
      { name: 'TwitterIcon', value: TwitterIcon },
      { name: 'TwitterShareButton', value: TwitterShareButton },
    ]
  },
  {
    module: 'next/head',
    exports: [
      { name: 'default', value: Head },
    ]
  },
  {
    module: 'react-scroll-parallax',
    exports: [
      { name: 'ParallaxBanner', value: ParallaxBanner },
    ]
  },
  {
    module: 'components/non-sitecore/ParallaxBackgroundImage',
    exports: [
      { name: 'ParallaxBackgroundImage', value: ParallaxBackgroundImage },
    ]
  },
  {
    module: 'components/non-sitecore/IconAccent',
    exports: [
      { name: 'IconAccent', value: IconAccent },
    ]
  },
  {
    module: 'src/components/search/PreviewSearch',
    exports: [
      { name: 'default', value: PreviewSearch_4de1a796917131c02c1d8f23d3df1bc9d5bbcf97 },
    ]
  },
  {
    module: 'components/utilities/LanguageSwitcher',
    exports: [
      { name: 'Default', value: Default },
    ]
  },
  {
    module: 'components/utilities/ThemeSwitcher',
    exports: [
      { name: 'Default', value: Default_82849cdc64a1386caf2bc2113719a7485562c8a0 },
    ]
  },
  {
    module: 'src/lib/sitecore-client',
    exports: [
      { name: 'default', value: client },
    ]
  },
  {
    module: '@sitecore-content-sdk/events',
    exports: [
      { name: 'pageView', value: pageView },
    ]
  },
  {
    module: 'sitecore.config',
    exports: [
      { name: 'default', value: config },
    ]
  }
] as ImportEntry[];

export default combineImportEntries(defaultImportEntries, importMap);
